name: Checks git

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        run: sudo docker login -u ${{ secrets.DOCKERHUB_USER }} -p ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: sudo docker-compose run --rm app sh -c "python manage.py test"
      - name: Lint
        run: sudo docker-compose run --rm app sh -c "flake8"
